(cl:defpackage komodo_speech-msg
  (:use )
  (:export
   "<KOMODOSPEECHSAYCOMMAND>"
   "KOMODOSPEECHSAYCOMMAND"
   "<KOMODOSPEECHSAYRESULT>"
   "KOMODOSPEECHSAYRESULT"
   "<KOMODOSPEECHRECCOMMAND>"
   "KOMODOSPEECHRECCOMMAND"
   "<KOMODOSPEECHRECRESULT>"
   "KOMODOSPEECHRECRESULT"
  ))

