(cl:defpackage komodo_speech-srv
  (:use )
  (:export
   "KOMODOSPEECHPROCESSING"
   "<KOMODOSPEECHPROCESSING-REQUEST>"
   "KOMODOSPEECHPROCESSING-REQUEST"
   "<KOMODOSPEECHPROCESSING-RESPONSE>"
   "KOMODOSPEECHPROCESSING-RESPONSE"
  ))

