(cl:defpackage komodo_speech-srv
  (:use )
  (:export
   "KOMODOSPEECHRUNNING"
   "<KOMODOSPEECHRUNNING-REQUEST>"
   "KOMODOSPEECHRUNNING-REQUEST"
   "<KOMODOSPEECHRUNNING-RESPONSE>"
   "KOMODOSPEECHRUNNING-RESPONSE"
  ))

