// Generated by gencpp from file komodo_speech/KomodoSpeechRunningResponse.msg
// DO NOT EDIT!


#ifndef KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNINGRESPONSE_H
#define KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace komodo_speech
{
template <class ContainerAllocator>
struct KomodoSpeechRunningResponse_
{
  typedef KomodoSpeechRunningResponse_<ContainerAllocator> Type;

  KomodoSpeechRunningResponse_()
    : processing(false)  {
    }
  KomodoSpeechRunningResponse_(const ContainerAllocator& _alloc)
    : processing(false)  {
    }



   typedef uint8_t _processing_type;
  _processing_type processing;




  typedef boost::shared_ptr< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> const> ConstPtr;

}; // struct KomodoSpeechRunningResponse_

typedef ::komodo_speech::KomodoSpeechRunningResponse_<std::allocator<void> > KomodoSpeechRunningResponse;

typedef boost::shared_ptr< ::komodo_speech::KomodoSpeechRunningResponse > KomodoSpeechRunningResponsePtr;
typedef boost::shared_ptr< ::komodo_speech::KomodoSpeechRunningResponse const> KomodoSpeechRunningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace komodo_speech

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'komodo_speech': ['/home/neowizard/school/komodo/komodo_speech/src/komodo_speech/msg'], 'std_msgs': ['/home/neowizard/school/komodo/ros_deb_catkin_ws/src/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14c43fbec2ed75ad470309f9d3538198";
  }

  static const char* value(const ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14c43fbec2ed75adULL;
  static const uint64_t static_value2 = 0x470309f9d3538198ULL;
};

template<class ContainerAllocator>
struct DataType< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "komodo_speech/KomodoSpeechRunningResponse";
  }

  static const char* value(const ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool processing\n\
\n\
";
  }

  static const char* value(const ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.processing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KomodoSpeechRunningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::komodo_speech::KomodoSpeechRunningResponse_<ContainerAllocator>& v)
  {
    s << indent << "processing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.processing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNINGRESPONSE_H
