/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/komodo/komodo_speech/src/komodo_speech/srv/KomodoSpeechRunning.srv
 *
 */


#ifndef KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNING_H
#define KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNING_H

#include <ros/service_traits.h>


#include <komodo_speech/KomodoSpeechRunningRequest.h>
#include <komodo_speech/KomodoSpeechRunningResponse.h>


namespace komodo_speech
{

struct KomodoSpeechRunning
{

typedef KomodoSpeechRunningRequest Request;
typedef KomodoSpeechRunningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KomodoSpeechRunning
} // namespace komodo_speech


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::komodo_speech::KomodoSpeechRunning > {
  static const char* value()
  {
    return "14c43fbec2ed75ad470309f9d3538198";
  }

  static const char* value(const ::komodo_speech::KomodoSpeechRunning&) { return value(); }
};

template<>
struct DataType< ::komodo_speech::KomodoSpeechRunning > {
  static const char* value()
  {
    return "komodo_speech/KomodoSpeechRunning";
  }

  static const char* value(const ::komodo_speech::KomodoSpeechRunning&) { return value(); }
};


// service_traits::MD5Sum< ::komodo_speech::KomodoSpeechRunningRequest> should match 
// service_traits::MD5Sum< ::komodo_speech::KomodoSpeechRunning > 
template<>
struct MD5Sum< ::komodo_speech::KomodoSpeechRunningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::komodo_speech::KomodoSpeechRunning >::value();
  }
  static const char* value(const ::komodo_speech::KomodoSpeechRunningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo_speech::KomodoSpeechRunningRequest> should match 
// service_traits::DataType< ::komodo_speech::KomodoSpeechRunning > 
template<>
struct DataType< ::komodo_speech::KomodoSpeechRunningRequest>
{
  static const char* value()
  {
    return DataType< ::komodo_speech::KomodoSpeechRunning >::value();
  }
  static const char* value(const ::komodo_speech::KomodoSpeechRunningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::komodo_speech::KomodoSpeechRunningResponse> should match 
// service_traits::MD5Sum< ::komodo_speech::KomodoSpeechRunning > 
template<>
struct MD5Sum< ::komodo_speech::KomodoSpeechRunningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::komodo_speech::KomodoSpeechRunning >::value();
  }
  static const char* value(const ::komodo_speech::KomodoSpeechRunningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::komodo_speech::KomodoSpeechRunningResponse> should match 
// service_traits::DataType< ::komodo_speech::KomodoSpeechRunning > 
template<>
struct DataType< ::komodo_speech::KomodoSpeechRunningResponse>
{
  static const char* value()
  {
    return DataType< ::komodo_speech::KomodoSpeechRunning >::value();
  }
  static const char* value(const ::komodo_speech::KomodoSpeechRunningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KOMODO_SPEECH_MESSAGE_KOMODOSPEECHRUNNING_H
